package com.llmcouncil.mobile.data
import android.content.Context
import android.net.Uri
import androidx.documentfile.provider.DocumentFile
import com.llmcouncil.mobile.model.*
import org.json.*
import java.text.SimpleDateFormat
import java.util.*
object ExportManager{fun exportRepoAudit(context:Context,treeUri:Uri,run:RepoAuditRun):String{val root=DocumentFile.fromTreeUri(context,treeUri)?:error("Folder unavailable");val project=dir(dir(root,"OmniCouncil"),safe(run.repoFullName.replace('/','_')));val name="${SimpleDateFormat("yyyy-MM-dd_HHmmss",Locale.UK).format(Date(run.startedAt))}_Repository-Audit_${run.commitSha.take(8)}";val ws=dir(project,name);val meta=dir(ws,"00_Audit-Metadata");val individual=dir(ws,"01_Individual-Reviews");val peer=dir(ws,"02_Peer-Reviews");val final=dir(ws,"04_Final-Report");val evidence=dir(ws,"05_Evidence");write(context,meta,"audit-summary.json","application/json",JSONObject().put("application","OmniCouncil").put("audit_standard_version",run.auditStandardVersion).put("repository",run.repoFullName).put("commit_sha",run.commitSha).put("scope_manifest_hash",run.scopeManifestHash).put("required_files",run.requiredFiles).put("excluded_files",run.excludedFiles).put("final_reviewer_model",run.chairmanModel).put("models",JSONArray(run.modelAudits.map{it.model})).toString(2));write(context,meta,"methodology.txt","text/plain","OmniCouncil Software Audit Standard v${run.auditStandardVersion}\nCoverage is counted only after valid per-file evidence is returned. Generic/refusal responses are rejected.\n");run.modelAudits.forEachIndexed{i,a->write(context,individual,"%02d_%s.md".format(i+1,safe(a.model)),"text/markdown","# Independent Evidence Audit\nModel: `${a.model}`\nEvidence coverage: ${a.coveredCount}/${a.requiredCount}\nComplete: ${a.complete}\n\n${a.error?:a.report}");write(context,evidence,"%02d_%s_batches.md".format(i+1,safe(a.model)),"text/markdown",a.batchReports.mapIndexed{n,r->"## Batch ${n+1}\n$r"}.joinToString("\n\n"))};run.peerReviews.forEachIndexed{i,r->write(context,peer,"%02d_peer.md".format(i+1),"text/markdown","Reviewer model: `${r.model}`\n\n${r.error?:r.text}")};write(context,evidence,"file-coverage.csv","text/csv",buildString{append("model,path,evidence_validated,batch,error\n");run.modelAudits.flatMap{it.coverage}.forEach{c->append("${csv(c.model)},${csv(c.path)},${c.covered},${c.batchIndex},${csv(c.error?:"")}\n")}});if(run.verificationMemo.isNotBlank())write(context,evidence,"verification.md","text/markdown",run.verificationMemo);write(context,final,"Final-OmniCouncil-Review.md","text/markdown","# Final OmniCouncil Repository Audit\n\nAudit Standard: v${run.auditStandardVersion}\nRepository: `${run.repoFullName}`\nCommit: `${run.commitSha}`\nScope: `${run.scopeManifestHash}`\nFinal Reviewer: `${run.chairmanModel}`\n\n${run.finalReport}");return "OmniCouncil/${project.name}/$name"}
 fun exportCouncilRun(context:Context,treeUri:Uri,run:CouncilRun,projectName:String="Council-Runs"):String{val root=DocumentFile.fromTreeUri(context,treeUri)?:error("Folder unavailable");val project=dir(dir(root,"OmniCouncil"),safe(projectName));val ws=dir(project,"${SimpleDateFormat("yyyy-MM-dd_HHmmss",Locale.UK).format(Date(run.startedAt))}_Council-Run");run.chairman?.let{write(context,ws,"Final-Answer.md","text/markdown",it.error?:it.text)};return "OmniCouncil/${project.name}/${ws.name}"}
 private fun dir(p:DocumentFile,n:String)=p.findFile(n)?.takeIf{it.isDirectory}?:p.createDirectory(n)?:error("Cannot create $n");private fun write(c:Context,p:DocumentFile,n:String,m:String,t:String){p.findFile(n)?.delete();val f=p.createFile(m,n)?:error("Cannot create $n");c.contentResolver.openOutputStream(f.uri,"wt")!!.bufferedWriter().use{it.write(t)}};private fun csv(v:String)="\"${v.replace("\"","\"\"")}\"";private fun safe(v:String)=v.replace(Regex("[^A-Za-z0-9._-]+"),"_").take(100)}
