package com.llmcouncil.mobile.data
import com.llmcouncil.mobile.model.*
import kotlinx.coroutines.*
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.*
import org.json.*
import java.io.IOException
import java.net.URLEncoder
import java.util.concurrent.TimeUnit
sealed class ApiFailure(message:String):Exception(message){class Authentication(message:String):ApiFailure(message);class Credits(message:String):ApiFailure(message);class RateLimit(message:String):ApiFailure(message);class Unavailable(message:String):ApiFailure(message);class Network(message:String):ApiFailure(message);class Other(message:String):ApiFailure(message)}
data class OpenRouterKeyStatus(val isFreeTier:Boolean,val limit:Double?,val limitRemaining:Double?,val usage:Double,val label:String)
class OpenRouterClient(private val settings:SecureSettings){
 private val client=OkHttpClient.Builder().connectTimeout(25,TimeUnit.SECONDS).readTimeout(150,TimeUnit.SECONDS).writeTimeout(30,TimeUnit.SECONDS).build();private val jsonType="application/json; charset=utf-8".toMediaType()
 suspend fun models():List<OpenRouterModel> = withContext(Dispatchers.IO){val all=mutableListOf<OpenRouterModel>();val failures=mutableListOf<String>();fun collect(b:()->List<OpenRouterModel>){try{all+=b()}catch(e:Exception){failures+=(e.message?:e.toString())}};if(settings.getOpenRouterKey().isNotBlank())collect{openRouterModels()};if(settings.getOpenAiKey().isNotBlank())collect{openAiModels()};if(settings.getAnthropicKey().isNotBlank())collect{anthropicModels()};if(settings.getGeminiKey().isNotBlank())collect{geminiModels()};if(all.isEmpty()&&failures.isNotEmpty())throw ApiFailure.Other(failures.joinToString(" · ").take(800));all.distinctBy{it.id}.sortedWith(compareBy<OpenRouterModel>{it.source.ordinal}.thenBy{it.name.lowercase()})}
 suspend fun openRouterKeyStatus():OpenRouterKeyStatus?=withContext(Dispatchers.IO){if(settings.getOpenRouterKey().isBlank())return@withContext null;val req=Request.Builder().url("https://openrouter.ai/api/v1/key").header("Authorization","Bearer ${settings.getOpenRouterKey()}").header("Accept","application/json").build();execute(req){body->val d=JSONObject(body).optJSONObject("data")?:JSONObject();OpenRouterKeyStatus(d.optBoolean("is_free_tier",false),d.optNullableDouble("limit"),d.optNullableDouble("limit_remaining"),d.optDouble("usage",0.0),d.optString("label",""))}}
 private fun openRouterModels():List<OpenRouterModel>{val req=Request.Builder().url("https://openrouter.ai/api/v1/models").header("Authorization","Bearer ${settings.getOpenRouterKey()}").build();return execute(req){body->val a=JSONObject(body).optJSONArray("data")?:JSONArray();buildList{for(i in 0 until a.length()){val o=a.optJSONObject(i)?:continue;val id=o.optString("id").trim();if(id.isBlank())continue;val p=o.optJSONObject("pricing");val arch=o.optJSONObject("architecture");add(OpenRouterModel(id,o.optString("name",id).ifBlank{id},ModelSource.OPENROUTER,id,o.optInt("context_length",0),p?.optString("prompt")?.toDoubleOrNull(),p?.optString("completion")?.toDoubleOrNull(),arch?.optJSONArray("input_modalities").toStringSet(),arch?.optJSONArray("output_modalities").toStringSet(),description=o.optString("description","")))}}}}
 private fun openAiModels():List<OpenRouterModel>{val req=Request.Builder().url("https://api.openai.com/v1/models").header("Authorization","Bearer ${settings.getOpenAiKey()}").build();return execute(req){body->val a=JSONObject(body).optJSONArray("data")?:JSONArray();buildList{for(i in 0 until a.length()){val id=a.optJSONObject(i)?.optString("id")?.trim().orEmpty();if(looksLikeOpenAiTextModel(id))add(OpenRouterModel(ModelSource.key(ModelSource.OPENAI,id),id,ModelSource.OPENAI,id,inputModalities=setOf("text"),outputModalities=setOf("text"),description="Direct OpenAI API model"))}}}}
 private fun anthropicModels():List<OpenRouterModel>{val req=Request.Builder().url("https://api.anthropic.com/v1/models?limit=100").header("x-api-key",settings.getAnthropicKey()).header("anthropic-version","2023-06-01").build();return execute(req){body->val a=JSONObject(body).optJSONArray("data")?:JSONArray();buildList{for(i in 0 until a.length()){val o=a.optJSONObject(i)?:continue;val id=o.optString("id").trim();if(id.isNotBlank())add(OpenRouterModel(ModelSource.key(ModelSource.ANTHROPIC,id),o.optString("display_name",id).ifBlank{id},ModelSource.ANTHROPIC,id,inputModalities=setOf("text"),outputModalities=setOf("text"),description="Direct Anthropic API model"))}}}}
 private fun geminiModels():List<OpenRouterModel>{val req=Request.Builder().url("https://generativelanguage.googleapis.com/v1beta/models").header("x-goog-api-key",settings.getGeminiKey()).build();return execute(req){body->val a=JSONObject(body).optJSONArray("models")?:JSONArray();buildList{for(i in 0 until a.length()){val o=a.optJSONObject(i)?:continue;val methods=o.optJSONArray("supportedGenerationMethods").toStringSet();if(methods.isNotEmpty()&&"generatecontent" !in methods)continue;val id=o.optString("name").removePrefix("models/").trim();if(id.isNotBlank()&&id.contains("gemini",true))add(OpenRouterModel(ModelSource.key(ModelSource.GEMINI,id),o.optString("displayName",id).ifBlank{id},ModelSource.GEMINI,id,o.optInt("inputTokenLimit",0),inputModalities=setOf("text"),outputModalities=setOf("text"),description=o.optString("description","Direct Gemini API model")))}}}}
 suspend fun chat(model:String,prompt:String,maxTokens:Int=2048,systemPrompt:String?=null):String=withContext(Dispatchers.IO){val source=ModelSource.fromKey(model);val id=ModelSource.apiIdFromKey(model);val audit=prompt.contains("repository",true)&&listOf("audit","scope","evidence").any{prompt.contains(it,true)};val attempts=if(audit)3 else 1;var last:Exception?=null;repeat(attempts){n->try{val text=when(source){ModelSource.OPENROUTER->openRouterChat(id,prompt,maxTokens,systemPrompt);ModelSource.OPENAI->openAiChat(id,prompt,maxTokens,systemPrompt);ModelSource.ANTHROPIC->anthropicChat(id,prompt,maxTokens,systemPrompt);ModelSource.GEMINI->geminiChat(id,prompt,maxTokens,systemPrompt)}.trim();if(!audit||text.length>=80)return@withContext text;last=ApiFailure.Unavailable("$model returned a non-substantive response")}catch(e:Exception){last=e};if(n+1<attempts)delay(750L*(n+1))};throw last?:ApiFailure.Unavailable("No usable response")}
 private fun messages(prompt:String,system:String?)=JSONArray().apply{if(!system.isNullOrBlank())put(JSONObject().put("role","system").put("content",system));put(JSONObject().put("role","user").put("content",prompt))}
 private fun openRouterChat(id:String,prompt:String,max:Int,system:String?):String{val payload=JSONObject().put("model",id).put("max_tokens",max.coerceIn(8,8192)).put("messages",messages(prompt,system));val req=Request.Builder().url("https://openrouter.ai/api/v1/chat/completions").header("Authorization","Bearer ${settings.getOpenRouterKey()}").header("Content-Type","application/json").post(payload.toString().toRequestBody(jsonType)).build();return execute(req){body->val root=JSONObject(body);root.optJSONObject("error")?.let{throw ApiFailure.Unavailable(it.optString("message",it.toString()))};val c=root.optJSONArray("choices")?:throw ApiFailure.Unavailable("OpenRouter returned no choices for $id");if(c.length()==0)throw ApiFailure.Unavailable("OpenRouter returned empty choices for $id");val x=c.optJSONObject(0)?:throw ApiFailure.Unavailable("Malformed choice");val content=x.optJSONObject("message")?.opt("content");val text=when(content){is String->content;is JSONArray->buildString{for(i in 0 until content.length()){val p=content.optJSONObject(i)?:continue;val v=p.optString("text").ifBlank{p.optString("content")};if(v.isNotBlank()){if(isNotEmpty())append('\n');append(v)}}};else->x.optString("text")}.trim();if(text.isBlank())throw ApiFailure.Unavailable("OpenRouter returned no text for $id");text}}
 private fun openAiChat(id:String,prompt:String,max:Int,system:String?):String{val payload=JSONObject().put("model",id).put("input",prompt).put("max_output_tokens",max.coerceIn(16,8192));if(!system.isNullOrBlank())payload.put("instructions",system);val req=Request.Builder().url("https://api.openai.com/v1/responses").header("Authorization","Bearer ${settings.getOpenAiKey()}").header("Content-Type","application/json").post(payload.toString().toRequestBody(jsonType)).build();return execute(req){body->val a=JSONObject(body).optJSONArray("output")?:JSONArray();buildString{for(i in 0 until a.length()){val c=a.optJSONObject(i)?.optJSONArray("content")?:continue;for(j in 0 until c.length()){val t=c.optJSONObject(j)?.optString("text").orEmpty();if(t.isNotBlank()){if(isNotEmpty())append('\n');append(t)}}}}}}
 private fun anthropicChat(id:String,prompt:String,max:Int,system:String?):String{val payload=JSONObject().put("model",id).put("max_tokens",max.coerceIn(16,8192)).put("messages",JSONArray().put(JSONObject().put("role","user").put("content",prompt)));if(!system.isNullOrBlank())payload.put("system",system);val req=Request.Builder().url("https://api.anthropic.com/v1/messages").header("x-api-key",settings.getAnthropicKey()).header("anthropic-version","2023-06-01").header("Content-Type","application/json").post(payload.toString().toRequestBody(jsonType)).build();return execute(req){body->val a=JSONObject(body).optJSONArray("content")?:JSONArray();buildString{for(i in 0 until a.length()){val t=a.optJSONObject(i)?.takeIf{it.optString("type")=="text"}?.optString("text").orEmpty();if(t.isNotBlank()){if(isNotEmpty())append('\n');append(t)}}}}}
 private fun geminiChat(id:String,prompt:String,max:Int,system:String?):String{val encoded=URLEncoder.encode(id,"UTF-8").replace("%2F","/");val payload=JSONObject().put("contents",JSONArray().put(JSONObject().put("role","user").put("parts",JSONArray().put(JSONObject().put("text",prompt))))).put("generationConfig",JSONObject().put("maxOutputTokens",max.coerceIn(16,8192)));if(!system.isNullOrBlank())payload.put("systemInstruction",JSONObject().put("parts",JSONArray().put(JSONObject().put("text",system))));val req=Request.Builder().url("https://generativelanguage.googleapis.com/v1beta/models/$encoded:generateContent").header("x-goog-api-key",settings.getGeminiKey()).header("Content-Type","application/json").post(payload.toString().toRequestBody(jsonType)).build();return execute(req){body->val a=JSONObject(body).optJSONArray("candidates")?:JSONArray();val p=a.optJSONObject(0)?.optJSONObject("content")?.optJSONArray("parts")?:JSONArray();buildString{for(i in 0 until p.length()){val t=p.optJSONObject(i)?.optString("text").orEmpty();if(t.isNotBlank()){if(isNotEmpty())append('\n');append(t)}}}}}
 private fun looksLikeOpenAiTextModel(id:String):Boolean{val s=id.lowercase();if(listOf("embedding","whisper","tts","image","dall-e","realtime","audio").any{s.contains(it)})return false;return s.startsWith("gpt-")||s.startsWith("o1")||s.startsWith("o3")||s.startsWith("o4")||s.startsWith("chatgpt-")||s.startsWith("codex-")}
 private fun <T> execute(request:Request,parser:(String)->T):T{try{client.newCall(request).execute().use{r->val body=r.body?.string().orEmpty();if(!r.isSuccessful)throw failure(r.code,body);return parser(body)}}catch(e:ApiFailure){throw e}catch(e:IOException){throw ApiFailure.Network(e.message?:e.toString())}catch(e:Exception){throw ApiFailure.Other(e.message?:e.toString())}}
 private fun JSONArray?.toStringSet():Set<String> = if(this==null)emptySet()else buildSet{for(i in 0 until length())optString(i).trim().lowercase().takeIf{it.isNotEmpty()}?.let(::add)}
 private fun JSONObject.optNullableDouble(n:String):Double?=if(!has(n)||isNull(n))null else optDouble(n).takeUnless{it.isNaN()}
 private fun failure(code:Int,body:String):ApiFailure{val clean=runCatching{JSONObject(body).optJSONObject("error")?.optString("message")?:JSONObject(body).optString("message")}.getOrNull().orEmpty().ifBlank{body.take(700)};return when(code){401,403->ApiFailure.Authentication(clean);402->ApiFailure.Credits(clean);429->ApiFailure.RateLimit(clean);404,408,502,503,504->ApiFailure.Unavailable(clean);else->ApiFailure.Other("HTTP $code — $clean")}}
}
