package com.llmcouncil.mobile.data
import android.content.Context
import com.llmcouncil.mobile.model.*
import org.json.*
import java.io.File
import java.util.zip.*
class RepoAuditCheckpointStore(context:Context){private val file=File(context.filesDir,"repo_audit_checkpoint_v5.json.gz");@Synchronized fun save(run:RepoAuditRun){val tmp=File(file.parentFile,file.name+".tmp");GZIPOutputStream(tmp.outputStream()).use{it.write(encode(run).toString().toByteArray())};if(!tmp.renameTo(file)){tmp.copyTo(file,true);tmp.delete()}};@Synchronized fun load():RepoAuditRun?{if(!file.exists())return null;return runCatching{decode(JSONObject(GZIPInputStream(file.inputStream()).bufferedReader().use{it.readText()}))}.getOrNull()};@Synchronized fun clear(){file.delete()}
 private fun encode(r:RepoAuditRun)=JSONObject().put("repo",r.repoFullName).put("ref",r.ref).put("commit",r.commitSha).put("scope",r.scopeManifestHash).put("standard",r.auditStandardVersion).put("stage",r.stage.name).put("required",r.requiredFiles).put("excluded",r.excludedFiles).put("chairman",r.chairmanModel).put("verification",r.verificationMemo).put("final",r.finalReport).put("started",r.startedAt).put("finished",r.finishedAt?:JSONObject.NULL).put("errors",JSONObject(r.errors)).put("audits",JSONArray().apply{r.modelAudits.forEach{a->put(JSONObject().put("model",a.model).put("report",a.report).put("complete",a.complete).put("error",a.error?:JSONObject.NULL).put("batches",JSONArray(a.batchReports)).put("coverage",JSONArray().apply{a.coverage.forEach{c->put(JSONObject().put("path",c.path).put("model",c.model).put("covered",c.covered).put("batch",c.batchIndex).put("error",c.error?:JSONObject.NULL))}}))}}).put("peer",JSONArray().apply{r.peerReviews.forEach{x->put(JSONObject().put("model",x.model).put("text",x.text).put("ranking",JSONArray(x.parsedRanking)).put("latency",x.latencyMs).put("error",x.error?:JSONObject.NULL))}}).put("aggregate",JSONArray().apply{r.aggregate.forEach{x->put(JSONObject().put("model",x.model).put("avg",x.averageRank).put("votes",x.votes))}}).put("excluded_manifest",JSONArray().apply{r.excludedManifest.forEach{f->put(JSONObject().put("path",f.path).put("sha",f.sha).put("size",f.size).put("category",f.category).put("reason",f.exclusionReason?:"excluded"))}})
 private fun decode(o:JSONObject):RepoAuditRun{val audits=mutableListOf<ModelRepoAudit>();val aa=o.optJSONArray("audits")?:JSONArray();for(i in 0 until aa.length()){val a=aa.getJSONObject(i);val batches=mutableListOf<String>();val ba=a.optJSONArray("batches")?:JSONArray();for(j in 0 until ba.length())batches+=ba.optString(j);val cov=mutableListOf<FileCoverage>();val ca=a.optJSONArray("coverage")?:JSONArray();for(j in 0 until ca.length()){val c=ca.getJSONObject(j);cov+=FileCoverage(c.optString("path"),c.optString("model"),c.optBoolean("covered"),c.optInt("batch"),if(c.isNull("error"))null else c.optString("error"))};audits+=ModelRepoAudit(a.optString("model"),a.optString("report"),cov,batches,a.optBoolean("complete"),if(a.isNull("error"))null else a.optString("error"))};val peer=mutableListOf<RankingReview>();val pa=o.optJSONArray("peer")?:JSONArray();for(i in 0 until pa.length()){val x=pa.getJSONObject(i);val rank=mutableListOf<String>();val ra=x.optJSONArray("ranking")?:JSONArray();for(j in 0 until ra.length())rank+=ra.optString(j);peer+=RankingReview(x.optString("model"),x.optString("text"),rank,x.optLong("latency"),if(x.isNull("error"))null else x.optString("error"))};val agg=mutableListOf<AggregateRank>();val ga=o.optJSONArray("aggregate")?:JSONArray();for(i in 0 until ga.length()){val x=ga.getJSONObject(i);agg+=AggregateRank(x.optString("model"),x.optDouble("avg"),x.optInt("votes"))};val ex=mutableListOf<RepoFile>();val ea=o.optJSONArray("excluded_manifest")?:JSONArray();for(i in 0 until ea.length()){val f=ea.getJSONObject(i);ex+=RepoFile(f.optString("path"),f.optString("sha"),f.optLong("size"),"",f.optString("category"),true,f.optString("reason"))};val er=o.optJSONObject("errors")?:JSONObject();val errors=buildMap<String,String>{er.keys().forEach{put(it,er.optString(it))}};return RepoAuditRun(o.optString("repo"),o.optString("ref"),o.optString("commit"),o.optString("scope"),o.optInt("standard",0),runCatching{RepoAuditStage.valueOf(o.optString("stage"))}.getOrDefault(RepoAuditStage.IDLE),o.optInt("required"),o.optInt("excluded"),audits,peer,agg,emptyList(),o.optString("final"),o.optString("chairman"),errors,o.optLong("started"),if(o.isNull("finished"))null else o.optLong("finished"),o.optString("verification"),ex)}
}
