package com.llmcouncil.mobile
import android.app.*
import android.content.*
import android.os.IBinder
import androidx.core.app.NotificationCompat
import com.llmcouncil.mobile.data.*
import com.llmcouncil.mobile.domain.*
import com.llmcouncil.mobile.model.*
import kotlinx.coroutines.*
class RepoAuditService:Service(){companion object{const val ACTION_START="com.llmcouncil.mobile.action.START_REPO_AUDIT";const val ACTION_CANCEL="com.llmcouncil.mobile.action.CANCEL_REPO_AUDIT";const val EXTRA_REPO="repo";const val EXTRA_REF="ref";private const val CHANNEL="repo_audit_runs";private const val ID=4405};private val scope=CoroutineScope(SupervisorJob()+Dispatchers.IO);private var active:Job?=null;override fun onCreate(){super.onCreate();RepoAuditRuntime.initialise(this);manager().createNotificationChannel(NotificationChannel(CHANNEL,"Repository audits",NotificationManager.IMPORTANCE_LOW))};override fun onStartCommand(i:Intent?,f:Int,s:Int):Int{when(i?.action){ACTION_CANCEL->{active?.cancel();RepoAuditRuntime.update(this,RepoAuditRuntime.run.value.copy(stage=RepoAuditStage.CANCELLED,finishedAt=System.currentTimeMillis()));stopSelf()};ACTION_START->{val r=i.getStringExtra(EXTRA_REPO).orEmpty();val ref=i.getStringExtra(EXTRA_REF).orEmpty();if(r.isNotBlank()&&active?.isActive!=true)start(r,ref)}};return START_REDELIVER_INTENT}
 private fun start(repoName:String,ref:String){startForeground(ID,note("Loading validated scope…",true));active=scope.launch{val settings=SecureSettings(this@RepoAuditService,true);val github=GitHubClient(settings);val engine=RepoAuditEngine(OpenRouterClient(settings),settings,ModelHealthDb(this@RepoAuditService));try{val approved=ScopeManifestStore(this@RepoAuditService).load(ref)?:error("Validated scope is missing or failed integrity verification");val checkpoint=RepoAuditRuntime.run.value.takeIf{it.repoFullName==repoName&&it.ref==ref&&it.scopeManifestHash==approved.manifestHash&&it.auditStandardVersion==AuditStandards.VERSION&&it.stage!=RepoAuditStage.COMPLETE};var state=RepoAuditRun(repoFullName=repoName,ref=ref,scopeManifestHash=approved.manifestHash,auditStandardVersion=AuditStandards.VERSION,stage=RepoAuditStage.SNAPSHOT,startedAt=checkpoint?.startedAt?:System.currentTimeMillis());RepoAuditRuntime.update(this@RepoAuditService,state);val repo=GitHubRepo(repoName,ref,false,"");val snapshot=github.snapshot(repo,ref,approved){c,t,p->manager().notify(ID,note("Snapshot $c/$t · ${p.takeLast(30)}",false,true,if(t==0)0 else c*100/t))};val resume=checkpoint?.takeIf{it.commitSha==snapshot.commitSha};state=(resume?:state).copy(commitSha=snapshot.commitSha,requiredFiles=snapshot.requiredFiles.size,excludedFiles=snapshot.excluded.size,excludedManifest=snapshot.excluded,stage=RepoAuditStage.INDEPENDENT,auditStandardVersion=AuditStandards.VERSION);RepoAuditRuntime.update(this@RepoAuditService,state);val result=engine.run(snapshot,approved.manifestHash,resume){u->RepoAuditRuntime.update(this@RepoAuditService,u);manager().notify(ID,note("${u.stage.name.replace('_',' ')} · ${u.modelAudits.count{it.complete}} evidence passes complete",u.stage in listOf(RepoAuditStage.INDEPENDENT,RepoAuditStage.PEER_REVIEW,RepoAuditStage.VERIFY,RepoAuditStage.CHAIRMAN)))};RepoAuditRuntime.update(this@RepoAuditService,result);if(result.stage==RepoAuditStage.COMPLETE&&result.finalReport.isNotBlank())RepoAuditHistoryDb(this@RepoAuditService).insertOrReplace(result.repoFullName,result.commitSha,result.scopeManifestHash,result.requiredFiles,result.excludedFiles,result.chairmanModel,result.finalReport,result.startedAt,result.finishedAt?:System.currentTimeMillis());manager().notify(ID,note(if(result.stage==RepoAuditStage.COMPLETE)"Repository audit finished" else "Repository audit stopped",false,false))}catch(e:CancellationException){RepoAuditRuntime.update(this@RepoAuditService,RepoAuditRuntime.run.value.copy(stage=RepoAuditStage.CANCELLED,finishedAt=System.currentTimeMillis()))}catch(e:Exception){val c=RepoAuditRuntime.run.value;RepoAuditRuntime.update(this@RepoAuditService,c.copy(stage=RepoAuditStage.ERROR,errors=c.errors+("Repository audit" to(e.message?:e.toString())),finishedAt=System.currentTimeMillis()));manager().notify(ID,note("Repository audit failed · tap for diagnostics",false,false))}finally{stopForeground(STOP_FOREGROUND_DETACH);stopSelf()}}}
 private fun manager()=getSystemService(Context.NOTIFICATION_SERVICE)as NotificationManager;private fun note(text:String,ind:Boolean,ongoing:Boolean=true,pct:Int?=null):Notification{val pending=PendingIntent.getActivity(this,ID,Intent(this,RepoAuditActivity::class.java),PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE);val b=NotificationCompat.Builder(this,CHANNEL).setSmallIcon(android.R.drawable.stat_notify_sync).setContentTitle("OmniCouncil · Repository Audit").setContentText(text).setContentIntent(pending).setOnlyAlertOnce(true).setOngoing(ongoing).setPriority(NotificationCompat.PRIORITY_LOW);when{pct!=null->b.setProgress(100,pct,false);ind->b.setProgress(0,0,true)};return b.build()};override fun onBind(i:Intent?):IBinder?=null}
