package com.llmcouncil.mobile

import android.Manifest
import android.content.Intent
import android.content.pm.PackageManager
import android.os.Build
import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.compose.setContent
import androidx.activity.enableEdgeToEdge
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.text.selection.SelectionContainer
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.PasswordVisualTransformation
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import androidx.core.content.ContextCompat
import androidx.lifecycle.Lifecycle
import androidx.lifecycle.LifecycleEventObserver
import androidx.lifecycle.ViewModelProvider
import androidx.lifecycle.compose.LocalLifecycleOwner
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import com.llmcouncil.mobile.data.RepoAuditHistoryItem
import com.llmcouncil.mobile.model.*
import java.text.DateFormat
import java.util.Date

class RepoAuditActivity:ComponentActivity(){
    private lateinit var vm:RepoAuditViewModel
    private val folderPicker=registerForActivityResult(ActivityResultContracts.OpenDocumentTree()){uri->if(uri!=null){runCatching{contentResolver.takePersistableUriPermission(uri,Intent.FLAG_GRANT_READ_URI_PERMISSION or Intent.FLAG_GRANT_WRITE_URI_PERMISSION)};vm.setExportTree(uri)}}
    override fun onCreate(savedInstanceState:Bundle?){super.onCreate(savedInstanceState);enableEdgeToEdge();vm=ViewModelProvider(this)[RepoAuditViewModel::class.java];setContent{MaterialTheme(colorScheme=if(androidx.compose.foundation.isSystemInDarkTheme())darkColorScheme()else lightColorScheme()){RepoAuditScreen(vm,{folderPicker.launch(null)}){finish()}}}}
}

@Composable private fun RepoAuditScreen(vm:RepoAuditViewModel,onChooseFolder:()->Unit,onBack:()->Unit){
    val repos by vm.repos.collectAsStateWithLifecycle();val branches by vm.branches.collectAsStateWithLifecycle();val history by vm.history.collectAsStateWithLifecycle();val loading by vm.loading.collectAsStateWithLifecycle();val message by vm.message.collectAsStateWithLifecycle();val run by vm.run.collectAsStateWithLifecycle();val scope by vm.scopePreview.collectAsStateWithLifecycle();val preflight by vm.preflight.collectAsStateWithLifecycle();val privacy by vm.privacyConfirmed.collectAsStateWithLifecycle();val allocationVersion by vm.auditAllocationVersion.collectAsStateWithLifecycle();val context=LocalContext.current
    var tokenPanel by rememberSaveable{mutableStateOf(!vm.githubConfigured())};var token by rememberSaveable{mutableStateOf("")};var outputPanel by rememberSaveable{mutableStateOf(false)};var search by rememberSaveable{mutableStateOf("")};var selectedName by rememberSaveable{mutableStateOf("")};var ref by rememberSaveable{mutableStateOf("")};var rules by rememberSaveable{mutableStateOf("")};var advancedRef by rememberSaveable{mutableStateOf(false)};var manifest by remember{mutableStateOf(false)};var mode by rememberSaveable{mutableStateOf(if(run.repoFullName.isNotBlank())"run" else "new")};var historyItem by remember{mutableStateOf<RepoAuditHistoryItem?>(null)}
    val owner=LocalLifecycleOwner.current;DisposableEffect(owner){val observer=LifecycleEventObserver{_,event->if(event==Lifecycle.Event.ON_RESUME)vm.refreshAuditAllocation()};owner.lifecycle.addObserver(observer);onDispose{owner.lifecycle.removeObserver(observer)}}
    LaunchedEffect(Unit){if(vm.githubConfigured())vm.loadRepos();vm.loadHistory()}
    val selected=repos.firstOrNull{it.fullName==selectedName};if(manifest&&scope!=null)ScopeDialog(scope!!,vm){manifest=false};historyItem?.let{HistoryDialog(it,{vm.deleteHistory(it.id);historyItem=null}){historyItem=null}}
    val running=run.stage in listOf(RepoAuditStage.SNAPSHOT,RepoAuditStage.INDEPENDENT,RepoAuditStage.PEER_REVIEW,RepoAuditStage.VERIFY,RepoAuditStage.CHAIRMAN);val notificationLauncher=rememberLauncherForActivityResult(ActivityResultContracts.RequestPermission()){}
    Scaffold(topBar={TopAppBar(title={Column{Text("Repository Audit",fontWeight=FontWeight.Bold);Text("OmniCouncil · v${BuildConfig.VERSION_NAME}",style=MaterialTheme.typography.labelSmall)}},navigationIcon={IconButton(onClick=onBack){Icon(Icons.Default.ArrowBack,"Back")}},actions={IconButton(onClick={tokenPanel=!tokenPanel}){Icon(Icons.Default.Key,"GitHub")};IconButton(onClick={outputPanel=!outputPanel}){Icon(Icons.Default.Folder,"Output")}})}){padding->
        LazyColumn(Modifier.fillMaxSize().padding(padding),contentPadding=PaddingValues(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){
            if(tokenPanel)item{GitHubCard(vm,token,{token=it},{token="";tokenPanel=false})};if(outputPanel)item{OutputCard(vm,onChooseFolder)};message?.let{item{NoticeCard(it,vm::clearMessage)}}
            if(run.repoFullName.isNotBlank()||history.isNotEmpty())item{Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){FilterChip(mode=="new",{mode="new"},label={Text("New audit")});FilterChip(mode=="run",{mode="run"},label={Text(if(running)"Active / history" else "Audit history")})}}
            if(mode=="run"){
                if(run.repoFullName.isNotBlank()){item{ProgressCard(run,vm)};if(run.modelAudits.isNotEmpty())item{EvidenceCard(run,vm)};if(run.peerReviews.isNotEmpty())item{PeerCard(run,vm)};if(run.verificationMemo.isNotBlank())item{LongTextCard("Verification",run.verificationMemo)};if(run.finalReport.isNotBlank())item{LongTextCard("Final report · ${vm.modelLabel(run.chairmanModel)}",run.finalReport)}}
                if(history.isNotEmpty()){item{Text("Previous completed audits",style=MaterialTheme.typography.titleMedium,fontWeight=FontWeight.Bold)};items(history,key={it.id}){h->ElevatedCard(Modifier.fillMaxWidth().clickable{historyItem=h}){ListItem(headlineContent={Text(h.repoFullName,fontWeight=FontWeight.SemiBold)},supportingContent={Text("${h.commitSha.take(10)} · ${h.requiredFiles} files · ${DateFormat.getDateTimeInstance().format(Date(h.finishedAt))}")},leadingContent={Icon(Icons.Default.History,null)},trailingContent={Icon(Icons.Default.ChevronRight,null)})}}}
            }else if(!running){
                if(!vm.githubConfigured())item{ElevatedCard(colors=CardDefaults.elevatedCardColors(containerColor=MaterialTheme.colorScheme.errorContainer)){Column(Modifier.padding(14.dp)){Text("Connect GitHub",fontWeight=FontWeight.Bold);Text("Tap the key icon and add a read token.")}}}
                else if(selected==null){item{Text("Choose repository",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);Text("Recently updated repositories appear first.",style=MaterialTheme.typography.bodySmall)};item{OutlinedTextField(search,{search=it},Modifier.fillMaxWidth(),label={Text("Search repositories")},leadingIcon={Icon(Icons.Default.Search,null)},trailingIcon={IconButton(onClick=vm::loadRepos){Icon(Icons.Default.Refresh,"Reload")}},singleLine=true)};if(loading)item{LinearProgressIndicator(Modifier.fillMaxWidth())};items(repos.filter{search.isBlank()||it.fullName.contains(search,true)||it.description.contains(search,true)},key={it.fullName}){repo->ElevatedCard(Modifier.fillMaxWidth().clickable{selectedName=repo.fullName;ref=repo.defaultBranch;rules=vm.scopeRules(repo.fullName);advancedRef=false;vm.clearScopePreview();vm.loadBranches(repo.fullName)}){ListItem(headlineContent={Text(repo.fullName,fontWeight=FontWeight.SemiBold)},supportingContent={Text("${if(repo.privateRepo)"Private" else "Public"} · ${repo.defaultBranch}${repo.description.takeIf{it.isNotBlank()}?.let{" · $it"}.orEmpty()}",maxLines=2,overflow=TextOverflow.Ellipsis)},leadingContent={Icon(if(repo.privateRepo)Icons.Default.Lock else Icons.Default.Public,null)},trailingContent={Icon(Icons.Default.ChevronRight,null)})}}}
                else{val repo=selected;item{Row(verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text("New repository audit",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);Text(repo.fullName)};TextButton(onClick={selectedName="";vm.clearBranches();vm.clearScopePreview()}){Text("Change")}}};item{StepCard("1","Repository & scope"){RevisionPicker(ref,branches,repo.defaultBranch,{ref=it;vm.clearScopePreview()},{advancedRef=!advancedRef});if(advancedRef)OutlinedTextField(ref,{ref=it;vm.clearScopePreview()},Modifier.fillMaxWidth(),label={Text("Tag / commit / revision")},singleLine=true);OutlinedTextField(rules,{rules=it;vm.clearScopePreview()},Modifier.fillMaxWidth(),label={Text("Optional scope rules")},placeholder={Text("exclude: docs/archive/**\ninclude: backend/migrations/**")},minLines=3,maxLines=7)}};item{StepCard("2","Review team"){val reviewers=vm.auditReviewerModels();Text("${reviewers.size} Reviewers + Final Reviewer");reviewers.forEachIndexed{i,id->Text("Reviewer ${i+1} · ${vm.modelLabel(id)}",style=MaterialTheme.typography.labelMedium)};Text("Final Reviewer · ${vm.modelLabel(vm.auditChairman())}",style=MaterialTheme.typography.labelMedium);OutlinedButton(onClick={context.startActivity(Intent(context,AuditModelAllocationActivity::class.java))}){Icon(Icons.Default.Groups,null);Spacer(Modifier.width(6.dp));Text("Configure team")}}};item{StepCard("3","Prepare scope"){Text("Before scope preparation, OmniCouncil checks model access and audit qualification. Unusable selections are replaced only before the run begins.",style=MaterialTheme.typography.bodySmall);Button(onClick={vm.prepareScope(repo,ref,rules)},enabled=!loading&&vm.auditAllocationReady(),modifier=Modifier.fillMaxWidth()){Icon(Icons.Default.AutoAwesome,null);Spacer(Modifier.width(6.dp));Text(if(scope==null)"Prepare audit scope" else "Rebuild audit scope")};if(loading)OutlinedButton(onClick=vm::cancelScopePreparation,modifier=Modifier.fillMaxWidth()){Text("Cancel preparation")}}};val p=scope?.takeIf{it.repoFullName==repo.fullName&&it.ref==ref.ifBlank{repo.defaultBranch}};if(p!=null)item{ScopeSummary(p){manifest=true}};if(p!=null&&p.unresolvedFiles>0)item{Button(onClick=vm::retryAutomaticScope,enabled=!loading,modifier=Modifier.fillMaxWidth()){Text("Retry ${p.unresolvedFiles} unresolved")}};if(p!=null&&p.unresolvedFiles==0&&preflight!=null){item{PreflightCard(preflight!!,privacy,{vm.setPrivacyConfirmed(it)},{if(Build.VERSION.SDK_INT>=33&&ContextCompat.checkSelfPermission(context,Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)notificationLauncher.launch(Manifest.permission.POST_NOTIFICATIONS)})};item{Button(onClick={vm.start(repo,ref);mode="run"},enabled=privacy&&!loading,modifier=Modifier.fillMaxWidth()){Icon(Icons.Default.PlayArrow,null);Spacer(Modifier.width(6.dp));Text("Start validated audit")}}}}
            }else if(running&&mode=="new")item{ElevatedCard{Column(Modifier.padding(14.dp)){Text("An audit is already running",fontWeight=FontWeight.Bold);TextButton(onClick={mode="run"}){Text("Open active audit")}}}}
        }
    }
}

@Composable private fun RevisionPicker(current:String,branches:List<String>,fallback:String,onSelect:(String)->Unit,onAdvanced:()->Unit){var open by remember{mutableStateOf(false)};Column{Box{OutlinedButton(onClick={open=true},modifier=Modifier.fillMaxWidth()){Icon(Icons.Default.AccountTree,null);Spacer(Modifier.width(6.dp));Text(current.ifBlank{fallback},Modifier.weight(1f),maxLines=1,overflow=TextOverflow.Ellipsis);Icon(Icons.Default.ArrowDropDown,null)};DropdownMenu(open,{open=false}){(if(branches.isEmpty())listOf(fallback)else branches).distinct().forEach{b->DropdownMenuItem(text={Text(b)},onClick={onSelect(b);open=false})}}};TextButton(onClick=onAdvanced){Text("Advanced revision")}}}
@Composable private fun StepCard(n:String,title:String,content:@Composable ColumnScope.()->Unit){ElevatedCard(Modifier.fillMaxWidth()){Column(Modifier.padding(14.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){Text("$n · $title",fontWeight=FontWeight.Bold);content()}}}
@Composable private fun GitHubCard(vm:RepoAuditViewModel,token:String,onToken:(String)->Unit,onSaved:()->Unit){ElevatedCard{Column(Modifier.padding(14.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){Text("GitHub access",fontWeight=FontWeight.Bold);OutlinedTextField(token,onToken,Modifier.fillMaxWidth(),label={Text("GitHub token")},visualTransformation=PasswordVisualTransformation(),singleLine=true);Row{Button(onClick={vm.saveGitHubToken(token);onSaved()},enabled=token.isNotBlank()){Text(if(vm.githubConfigured())"Replace" else "Connect")};if(vm.githubConfigured())TextButton(onClick=vm::disconnectGitHub){Text("Disconnect")}}}}}
@Composable private fun OutputCard(vm:RepoAuditViewModel,onChooseFolder:()->Unit){ElevatedCard{Column(Modifier.padding(14.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){Text("Exports",fontWeight=FontWeight.Bold);OutlinedButton(onClick=onChooseFolder){Text("Choose folder")};Button(onClick=vm::exportCurrent,enabled=vm.run.value.repoFullName.isNotBlank()){Text("Export audit")}}}}
@Composable private fun NoticeCard(text:String,onDismiss:()->Unit){ElevatedCard{Row(Modifier.padding(12.dp),verticalAlignment=Alignment.CenterVertically){Icon(Icons.Default.Info,null);Spacer(Modifier.width(8.dp));Text(text,Modifier.weight(1f),style=MaterialTheme.typography.bodySmall);IconButton(onClick=onDismiss){Icon(Icons.Default.Close,"Dismiss")}}}}
@Composable private fun ScopeSummary(p:AuditScopePreview,onAdvanced:()->Unit){ElevatedCard{Column(Modifier.padding(14.dp),verticalArrangement=Arrangement.spacedBy(5.dp)){Text("Scope result",fontWeight=FontWeight.Bold);Text("${p.totalTrackedFiles} tracked · ${p.requiredFiles} included · ${p.excludedFiles} excluded · ${p.unresolvedFiles} unresolved");Text("Commit ${p.commitSha.take(12)} · ${p.manifestHash.take(12)}",style=MaterialTheme.typography.labelSmall);if(p.validationSummary.isNotBlank())Text(p.validationSummary,style=MaterialTheme.typography.bodySmall);TextButton(onClick=onAdvanced){Text("Advanced inspection")}}}}
@Composable private fun PreflightCard(p:AuditPreflight,privacy:Boolean,onPrivacy:(Boolean)->Unit,onNotifications:()->Unit){ElevatedCard(colors=CardDefaults.elevatedCardColors(containerColor=MaterialTheme.colorScheme.secondaryContainer)){Column(Modifier.padding(14.dp),verticalArrangement=Arrangement.spacedBy(5.dp)){Text("4 · Preflight · Audit Standard v${p.methodologyVersion}",fontWeight=FontWeight.Bold);Text("${p.requiredFiles} files · ${p.reviewers} evidence models · ~${p.estimatedRequests} requests");Text("Estimated duration ${p.estimatedMinutesLow}–${p.estimatedMinutesHigh} min",style=MaterialTheme.typography.bodySmall);Text("Live team readiness",fontWeight=FontWeight.SemiBold);p.teamReadiness.forEach{Text("• $it",style=MaterialTheme.typography.labelSmall)};Text("Scope fingerprint ${p.manifestHash.take(16)}…",style=MaterialTheme.typography.labelSmall);Row(verticalAlignment=Alignment.Top){Checkbox(privacy,onPrivacy);Text("I understand the validated repository material is sanitized and sent to the selected model providers.",Modifier.padding(top=10.dp),style=MaterialTheme.typography.bodySmall)};TextButton(onClick=onNotifications){Text("Enable progress notifications")}}}}
@Composable private fun ProgressCard(run:RepoAuditRun,vm:RepoAuditViewModel){val reviewerIds=vm.auditReviewerModels();val finalId=vm.auditChairman();val running=run.stage in listOf(RepoAuditStage.SNAPSHOT,RepoAuditStage.INDEPENDENT,RepoAuditStage.PEER_REVIEW,RepoAuditStage.VERIFY,RepoAuditStage.CHAIRMAN);ElevatedCard(colors=if(run.stage==RepoAuditStage.ERROR)CardDefaults.elevatedCardColors(containerColor=MaterialTheme.colorScheme.errorContainer)else CardDefaults.elevatedCardColors()){Column(Modifier.padding(14.dp),verticalArrangement=Arrangement.spacedBy(5.dp)){Text(run.repoFullName,fontWeight=FontWeight.Bold);Text("Commit ${run.commitSha.take(12)} · scope ${run.scopeManifestHash.take(12)}",style=MaterialTheme.typography.bodySmall);Text("Stage ${run.stage.name.replace('_',' ')} · Standard v${run.auditStandardVersion}",fontWeight=FontWeight.SemiBold);Text("${run.requiredFiles} files");run.modelAudits.forEach{a->val idx=reviewerIds.indexOf(a.model);val role=when{idx>=0&&a.model==finalId->"Reviewer ${idx+1} + Final Reviewer";idx>=0->"Reviewer ${idx+1}";a.model==finalId->"Final Reviewer";else->"Reviewer"};val pct=if(a.requiredCount==0)0 else a.coveredCount*100/a.requiredCount;Text("$role — ${vm.modelLabel(a.model)}",fontWeight=FontWeight.SemiBold,style=MaterialTheme.typography.bodySmall);Text("${a.coveredCount}/${a.requiredCount} evidence-validated ($pct%)${if(a.complete)" ✓" else ""}",style=MaterialTheme.typography.labelSmall);a.error?.let{Text(it,color=MaterialTheme.colorScheme.error,style=MaterialTheme.typography.labelSmall)}};run.errors.forEach{(k,v)->Text("$k: $v",color=MaterialTheme.colorScheme.error)};if(running)OutlinedButton(onClick=vm::cancel){Text("Cancel")}else TextButton(onClick=vm::clear){Text("Clear run")}}}}
@Composable private fun EvidenceCard(run:RepoAuditRun,vm:RepoAuditViewModel){var expanded by remember{mutableStateOf(setOf<String>())};val reviewerIds=vm.auditReviewerModels();ElevatedCard{Column(Modifier.padding(14.dp)){Text("Independent evidence passes",fontWeight=FontWeight.Bold);run.modelAudits.forEach{a->HorizontalDivider(Modifier.padding(vertical=8.dp));val full=a.model in expanded;val idx=reviewerIds.indexOf(a.model);Text(if(idx>=0)"Reviewer ${idx+1}" else "Final Reviewer evidence pass",fontWeight=FontWeight.SemiBold);Text(vm.modelLabel(a.model),style=MaterialTheme.typography.bodySmall);Text("${a.coveredCount}/${a.requiredCount} validated · ${if(a.complete)"complete" else "incomplete"}",style=MaterialTheme.typography.labelSmall);a.error?.let{Text(it,color=MaterialTheme.colorScheme.error)};if(a.report.isNotBlank()){SelectionContainer{Text(a.report,maxLines=if(full)Int.MAX_VALUE else 9,overflow=if(full)TextOverflow.Clip else TextOverflow.Ellipsis)};TextButton(onClick={expanded=if(full)expanded-a.model else expanded+a.model}){Text(if(full)"Collapse" else "Show report")}}}}}}
@Composable private fun PeerCard(run:RepoAuditRun,vm:RepoAuditViewModel){var expanded by remember{mutableStateOf(false)};ElevatedCard{Column(Modifier.padding(14.dp)){Text("Anonymous peer review",fontWeight=FontWeight.Bold);run.aggregate.forEachIndexed{i,r->Text("${i+1}. ${r.model} · avg ${r.averageRank} · ${r.votes} votes")};TextButton(onClick={expanded=!expanded}){Text(if(expanded)"Hide reviews" else "Show reviews")};if(expanded)run.peerReviews.forEachIndexed{i,r->HorizontalDivider(Modifier.padding(vertical=6.dp));Text("Peer reviewer ${i+1} — ${vm.modelLabel(r.model)}",fontWeight=FontWeight.SemiBold);SelectionContainer{Text(r.error?:r.text)}}}}}
@Composable private fun LongTextCard(title:String,text:String){var full by remember{mutableStateOf(false)};ElevatedCard{Column(Modifier.padding(14.dp)){Text(title,fontWeight=FontWeight.Bold);SelectionContainer{Text(text,maxLines=if(full)Int.MAX_VALUE else 16,overflow=if(full)TextOverflow.Clip else TextOverflow.Ellipsis)};TextButton(onClick={full=!full}){Text(if(full)"Collapse" else "Show full")}}}}
@Composable private fun HistoryDialog(item:RepoAuditHistoryItem,onDelete:()->Unit,onDismiss:()->Unit){AlertDialog(onDismissRequest=onDismiss,title={Text(item.repoFullName)},text={Column(Modifier.heightIn(max=620.dp)){Text("Commit ${item.commitSha.take(12)} · ${item.requiredFiles} files");Text("Final Reviewer: ${rawModelLabel(item.finalReviewer)}");HorizontalDivider();SelectionContainer{LazyColumn{item{Text(item.finalReport)}}}}},confirmButton={TextButton(onClick=onDismiss){Text("Close")}},dismissButton={TextButton(onClick=onDelete){Text("Delete")}})}
@Composable private fun ScopeDialog(p:AuditScopePreview,vm:RepoAuditViewModel,onDismiss:()->Unit){var q by rememberSaveable{mutableStateOf("")};val filtered=p.manifest.filter{q.isBlank()||it.path.contains(q,true)||it.reason.contains(q,true)};AlertDialog(onDismissRequest=onDismiss,title={Text("Scope · ${filtered.size}/${p.totalTrackedFiles}")},confirmButton={TextButton(onClick=onDismiss){Text("Done")}},text={Column(Modifier.heightIn(max=620.dp)){OutlinedTextField(q,{q=it},Modifier.fillMaxWidth(),label={Text("Search")});LazyColumn{items(filtered,key={it.path}){e->ListItem(headlineContent={Text(e.path,maxLines=2)},supportingContent={Text("${e.status} · ${e.reason}",maxLines=2)},trailingContent={if(!e.decisionSource.startsWith("hard-rule"))Row{TextButton(onClick={vm.overrideScope(e.path,AuditScopeStatus.REQUIRED)}){Text("In")};TextButton(onClick={vm.overrideScope(e.path,AuditScopeStatus.EXCLUDED)}){Text("Out")}}})}}}})}
private fun rawModelLabel(id:String)=if(id.isBlank())"Not assigned" else "${ModelSource.apiIdFromKey(id)} · ${ModelSource.fromKey(id).displayName}"
