package com.llmcouncil.mobile
import android.app.Application
import android.content.Intent
import android.net.Uri
import androidx.core.content.ContextCompat
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.viewModelScope
import com.llmcouncil.mobile.data.*
import com.llmcouncil.mobile.domain.*
import com.llmcouncil.mobile.model.*
import kotlinx.coroutines.*
import kotlinx.coroutines.flow.*
import kotlin.math.ceil
class RepoAuditViewModel(private val app:Application):AndroidViewModel(app){
 private val settings=SecureSettings(app);private val ai=OpenRouterClient(settings);private val health=ModelHealthDb(app);private val qualifier=ModelAuditQualifier(ai,health);private val github=GitHubClient(settings);private val refs=GitHubRefsClient(settings);private val scopeStore=ScopeManifestStore(app);private val rulesStore=AuditScopeRulesStore(app);private val scopeValidator=ScopeValidationEngine(ai,settings,github);private val historyDb=RepoAuditHistoryDb(app);val run:StateFlow<RepoAuditRun> = RepoAuditRuntime.run
 private val _repos=MutableStateFlow<List<GitHubRepo>>(emptyList());val repos=_repos.asStateFlow();private val _branches=MutableStateFlow<List<String>>(emptyList());val branches=_branches.asStateFlow();private val _history=MutableStateFlow<List<RepoAuditHistoryItem>>(emptyList());val history=_history.asStateFlow();private val _loading=MutableStateFlow(false);val loading=_loading.asStateFlow();private val _message=MutableStateFlow<String?>(null);val message=_message.asStateFlow();private val _scope=MutableStateFlow<AuditScopePreview?>(null);val scopePreview=_scope.asStateFlow();private val _preflight=MutableStateFlow<AuditPreflight?>(null);val preflight=_preflight.asStateFlow();private val _allocation=MutableStateFlow(0);val auditAllocationVersion=_allocation.asStateFlow();private val _privacy=MutableStateFlow(false);val privacyConfirmed=_privacy.asStateFlow();private var scopeJob:Job?=null;private var labels:Map<String,String> = emptyMap();private var readiness:List<String> = emptyList()
 init{RepoAuditRuntime.initialise(app);CouncilRuntime.initialise(app);loadHistory()}
 fun githubConfigured()=settings.getGitHubToken().isNotBlank();fun saveGitHubToken(v:String){settings.setGitHubToken(v.trim());if(v.isNotBlank())loadRepos()};fun disconnectGitHub(){settings.setGitHubToken("");_repos.value=emptyList();_branches.value=emptyList();_scope.value=null;_preflight.value=null};fun loadRepos(){if(_loading.value)return;viewModelScope.launch{_loading.value=true;try{_repos.value=github.listRepos()}catch(e:Exception){_message.value=friendly(e,"GitHub repositories")}finally{_loading.value=false}}};fun loadBranches(r:String){viewModelScope.launch{try{_branches.value=refs.branches(r)}catch(e:Exception){_branches.value=emptyList();_message.value=friendly(e,"Branch list")}}};fun clearBranches(){_branches.value=emptyList()};fun loadHistory(){viewModelScope.launch{_history.value=withContext(Dispatchers.IO){historyDb.list()}}};fun deleteHistory(id:Long){viewModelScope.launch{withContext(Dispatchers.IO){historyDb.delete(id)};loadHistory()}}
 fun scopeRules(r:String)=rulesStore.get(r);fun auditReviewerModels()=settings.auditReviewerModels().filter{it.isNotBlank()};fun auditChairman()=settings.auditChairman();fun auditAllocationReady():Boolean{val r=auditReviewerModels();return r.size>=2&&r.distinct().size==r.size&&auditChairman().isNotBlank()};fun refreshAuditAllocation(){_allocation.value++;_preflight.value=_scope.value?.takeIf{it.unresolvedFiles==0}?.let(::makePreflight)};fun setPrivacyConfirmed(v:Boolean){_privacy.value=v};fun modelLabel(id:String)=if(id.isBlank())"Not assigned" else labels[id]?:"${ModelSource.apiIdFromKey(id)} · ${ModelSource.fromKey(id).displayName}"
 fun prepareScope(repo:GitHubRepo,ref:String,rules:String){if(_loading.value)return;if(!auditAllocationReady()){_message.value="Configure at least two distinct Reviewers and one Final Reviewer first.";return};rulesStore.set(repo.fullName,rules);_privacy.value=false;scopeJob=viewModelScope.launch{_loading.value=true;_scope.value=null;_preflight.value=null;try{_message.value="Qualifying model access and audit capability…";ensureTeam();_message.value="Mapping repository scope…";val d=github.previewScope(repo,ref.ifBlank{repo.defaultBranch},rules);_scope.value=d;scopeStore.save(d);val p=if(d.unresolvedFiles==0)d.copy(validationSummary="Scope preparation complete.")else scopeValidator.validate(d){_message.value=it};_scope.value=p;scopeStore.save(p);_message.value=p.validationSummary;if(p.unresolvedFiles==0)_preflight.value=makePreflight(p)}catch(e:CancellationException){_message.value="Scope preparation cancelled"}catch(e:Exception){_message.value=friendly(e,"Scope preparation")}finally{_loading.value=false;scopeJob=null}}}
 fun cancelScopePreparation(){scopeJob?.cancel()};fun retryAutomaticScope(){val c=_scope.value?:return;scopeJob=viewModelScope.launch{_loading.value=true;try{ensureTeam();val p=scopeValidator.validate(c){_message.value=it};_scope.value=p;scopeStore.save(p);if(p.unresolvedFiles==0)_preflight.value=makePreflight(p)}catch(e:Exception){_message.value=friendly(e,"Scope retry")}finally{_loading.value=false}}};fun previewScope(repo:GitHubRepo,ref:String,rules:String)=prepareScope(repo,ref,rules);fun validateScope()=retryAutomaticScope();fun overrideScope(path:String,status:AuditScopeStatus){val c=_scope.value?:return;val u=c.copy(manifest=c.manifest.map{if(it.path==path)it.copy(status=status,reason="manual override",confidence=100,decisionSource="user")else it});_scope.value=u;scopeStore.save(u);_preflight.value=if(u.unresolvedFiles==0)makePreflight(u)else null;_privacy.value=false};fun clearScopePreview(){_scope.value=null;_preflight.value=null;_privacy.value=false}
 fun start(repo:GitHubRepo,ref:String){val p=_scope.value?:run{_message.value="Prepare scope first.";return};if(p.unresolvedFiles>0||p.requiredFiles<=0){_message.value="Audit scope is not ready.";return};if(!_privacy.value){_message.value="Confirm the preflight first.";return};viewModelScope.launch{_loading.value=true;try{val oldR=auditReviewerModels();val oldF=auditChairman();_message.value="Running final live readiness check…";ensureTeam();_preflight.value=makePreflight(p);if(oldR!=auditReviewerModels()||oldF!=auditChairman()){_privacy.value=false;_message.value="An unavailable model was replaced. Review the updated team and confirm preflight again.";return@launch};scopeStore.save(p);ContextCompat.startForegroundService(app,Intent(app,RepoAuditService::class.java).apply{action=RepoAuditService.ACTION_START;putExtra(RepoAuditService.EXTRA_REPO,repo.fullName);putExtra(RepoAuditService.EXTRA_REF,p.commitSha)});_message.value="Audit pinned to ${p.commitSha.take(12)} · Standard v${AuditStandards.VERSION}"}catch(e:Exception){_message.value=friendly(e,"Audit readiness")}finally{_loading.value=false}}}
 private suspend fun ensureTeam(){val cat=ai.models().filter(::eligible);labels=cat.associate{it.id to "${it.name} · ${it.source.displayName}"};val q=qualifier.qualifyTeam(auditReviewerModels(),auditChairman(),cat);if(q.reviewers.size<2||q.finalReviewer.isBlank())throw IllegalStateException("No complete audit-capable team is currently available. ${q.qualifications.filter{!it.ready}.joinToString(" · "){"${modelLabel(it.modelId)}: ${it.reason}"}.take(700)}");if(q.reviewers!=auditReviewerModels()||q.finalReviewer!=auditChairman()){settings.setAuditReviewerModels(q.reviewers);settings.setAuditChairman(q.finalReviewer);_allocation.value++};readiness=q.reviewers.mapIndexed{i,id->"Reviewer ${i+1}: ${modelLabel(id)} — qualified"}+"Final Reviewer: ${modelLabel(q.finalReviewer)} — qualified";if(q.replacements.isNotEmpty())_message.value="Unavailable models replaced before run: "+q.replacements.joinToString{(a,b)->"${modelLabel(a)} → ${modelLabel(b)}"}}
 private fun eligible(m:OpenRouterModel)=m.acceptsText&&m.returnsText&&m.apiId!="openrouter/auto"&&m.apiId!="openrouter/free"&&!listOf("embedding","rerank","moderation","whisper","transcription","tts","image-generation","video-generation").any{"${m.apiId} ${m.name}".contains(it,true)}
 fun cancel(){app.startService(Intent(app,RepoAuditService::class.java).apply{action=RepoAuditService.ACTION_CANCEL})};fun clear(){RepoAuditRuntime.clear(app)};fun setExportTree(u:Uri){settings.setExportTreeUri(u.toString())};fun exportTree()=settings.exportTreeUri()?.let(Uri::parse);fun exportCurrent(){val u=exportTree()?:run{_message.value="Choose export folder first";return};viewModelScope.launch{try{_message.value="Exported to "+withContext(Dispatchers.IO){ExportManager.exportRepoAudit(app,u,run.value)}}catch(e:Exception){_message.value=friendly(e,"Export")}}};fun clearMessage(){_message.value=null}
 private fun makePreflight(p:AuditScopePreview):AuditPreflight{val ms=(auditReviewerModels()+auditChairman()).distinct();val chars=p.manifest.filter{it.status==AuditScopeStatus.REQUIRED}.sumOf{it.size}.coerceAtLeast(1);val batches=ceil(chars/30000.0).toInt().coerceAtLeast(1);val requests=ms.size*batches+ms.size*2+8;val minutes=(requests*.12).coerceAtLeast(1.0);return AuditPreflight(p.requiredFiles,p.excludedFiles,ms.size,batches,requests,chars*ms.size,requests*1900L,minutes.toInt().coerceAtLeast(1),(minutes*2.5).toInt().coerceAtLeast(3),p.manifestHash,ms.map{ModelSource.fromKey(it).displayName}.distinct(),readiness.ifEmpty{auditReviewerModels().mapIndexed{i,id->"Reviewer ${i+1}: ${modelLabel(id)}"}+"Final Reviewer: ${modelLabel(auditChairman())}"},AuditStandards.VERSION)}
 private fun friendly(e:Exception,c:String):String{val r=e.message?:e.toString();val l=r.lowercase();return when{"credit" in l||"402" in l->"$c blocked: provider credits are insufficient; a qualified zero-cost alternative will be preferred when available.";"unable to resolve host" in l->"$c paused: network unavailable.";"refus" in l||"ground" in l->"$c blocked: a model did not produce repository-grounded evidence.";else->"$c failed: ${r.take(700)}"}}
}
